<div align="center">
<table cellspacing="0" cellpadding="0" width="100%">
    <tr class="header">
    <?php if($adminDelete): ?>
    <td class="header" align="center">Kick</td>
    <? endif; ?>
    <td class="header" align="center">Character Name</td>
    <td class="header" align="center">Player Name</td>
    <?php if ($admin): ?>
    <td class="header" align="center">IP</td>
    <td class="header" align="center">CD Key</td>
    <? endif; ?>
    </tr>